DROP DATABASE IF EXISTS MRVBIB;
-- DROP USER IF EXISTS 'coletor'@'localhost';

CREATE DATABASE MRVBIB;
CREATE USER 'coletor'@'localhost' IDENTIFIED BY 'ifes2017';
GRANT INSERT, SELECT ON MRVBIB.* TO 'coletor'@'localhost'; 

USE MRVBIB;

CREATE TABLE DADO_GPS
(
	DADO_ID_DADO_GPS		INT NOT NULL AUTO_INCREMENT,
	DADO_CD_VEICULO			CHAR(4) NOT NULL,
	DADO_VL_LATITUDE 		DECIMAL(10, 6) NOT NULL,
	DADO_SG_ORIENTACAO_LATITUDE	CHAR(1) NOT NULL,
	DADO_VL_LONGITUDE 		DECIMAL(10,6) NOT NULL,
	DADO_SG_ORIENTACAO_LONGITUDE	CHAR(1) NOT NULL,
	DADO_VL_VELOCIDADE 		DECIMAL(10, 6) NOT NULL, 
	DADO_DT_CAPTURA			DATETIME NOT NULL,
	DADO_DT_REGISTRO		DATETIME NOT NULL,

	PRIMARY KEY(DADO_ID_DADO_GPS)
);


