USE "NOME DO BANCO";

CREATE TABLE COLETOR
(	
	COLE_ID_COLETOR 				INT				NOT NULL 	AUTO INCREMENT,
	COLE_DT_REGISTRO				DATETIME 		NOT NULL,
	PRIMARY KEY(COLE_ID_COLETOR)
);

CREATE TABLE LINHA
(
	LINH_ID_LINHA 					INT 			NOT NULL 	AUTO INCREMENT,
	LINH_DT_REGISTRO				DATETIME		NOT NULL,
	LINH_NM_ORIGEM					VARCHAR(45)		NOT NULL,
	LH_NM_DESTINO 					VARCHAR(45)		NOT NULL,
	PRIMARY KEY(LINH_ID_LINHA)
);

CREATE TABLE VEICULO
(
	VEIC_ID_VEICULO					VARCHAR(7) 		NOT NULL,
	VEIC_TX_MODELO					VARCHAR(45)		NOT NULL,
	VEIC_DT_REGISTRO				DATETIME		NOT NULL,
	PRIMARY KEY(VEIC_ID_VEICULO)
);

CREATE TABLE TERMINAL
(
	TERM_ID_TERMINAL				INT 			NOT NULL	AUTO INCREMENT,
	TERM_DT_REGISTRO				DATETIME		NOT NULL,
	TERM_NM_NOME					VARCHAR(45)		NOT NULL,
	PRIMARY KEY(TERM_ID_TERMINAL)
);

CREATE TABLE DIAS_SEMANA
(
	DIAS_ID_DIAS_SEMANA	 			INT 			NOT NULL 	AUTO INCREMENT,
	DIAS_NM_DIA			 			VARCHAR(45)	NOT NULL,
	PRIMARY KEY(DIAS_ID_DIAS_SEMANA)
);

CREATE TABLE FERIADO
(	
	FERI_ID_FERIADO					INT 			NOT NULL	AUTO INCREMENT,
	FERI_DT_DIA						VARCHAR			NOT NULL,
	PRIMARY KEY(FERI_ID_FERIADO)
);

CREATE TABLE PONTO_PARADA
(	
	POPA_ID_PONTO_PARADA			INT 			NOT NULL, 	AUTO INCREMENT,
	POPA_DC_PONTO_PARADA			VARCHAR(256)	NOT NULL,
	POPA_VL_LATITUDE				DECIMAL			NOT NULL,
	POPA_VL_LONGITUDE				DECIMAL			NOT NULL,
	POPA_DT_REGISTRO				DATETIME		NOT NULL,
	PRIMARY KEY(POPA_ID_PONTO_PARADA)
);

CREATE TABLE DADO_GPS
(
	DADO_ID_DADO_GPS				INT 			NOT NULL, 	AUTO INCREMENT,
	COLE_ID_COLETOR					INT 			NOT NULL,
	DADO_VL_LATITUDE				DECIMAL			NOT NULL,
	DADO_SG_ORIENTACAO_LATITUDE		CHAR			NOT NULL,
	DADO_VL_LONGITUDE				DECIMAL			NOT NULL,
	DADO_SG_ORIENTACAO_LONGITUDE	CHAR 			NOT NULL,
	DADO_VL_VELOCIDADE				DECIMAL			NOT NULL,
	DADO_DT_CAPTURA					DATETIME		NOT NULL,
	DADO_DT_REGISTRO				DATETIME		NOT NULL,
	PRIMARY KEY(DADO_ID_DADO_GPS),
	FOREIGN KEY(COLE_ID_COLETOR) REFERENCES COLETOR(COLE_ID_COLETOR)
);

CREATE TABLE COLETOR_VEICULO
(
	COVE_ID_COLETOR_VEICULO			INT 			NOT NULL 	AUTO INCREMENT,
	COVE_DT_REGISTRO				DATETIME		NOT NULL,
	VEIC_ID_VEICULO					VARCHAR(7) 		NOT NULL,
	COLE_ID_COLETOR					INT 			NOT NULL,
	PRIMARY KEY(COVE_ID_COLETOR_VEICULO),
	FOREIGN KEY(VEIC_ID_VEICULO) REFERENCES VEICULO(VEIC_ID_VEICULO),
	FOREIGN KEY(COLE_ID_COLETOR) REFERENCES	COLETOR(COLE_ID_COLETOR)
);

CREATE TABLE PONTO_PARADA_LINHA
(	
	LINH_ID_LINHA 					INT 			NOT NULL,
	POPA_ID_PONTO_PARADA			INT 			NOT NULL,
	POLI_DT_REGISTRO				DATETIME		NOT NULL,
	PRIMARY KEY(LINH_ID_LINHA,POPA_ID_PONTO_PARADA)
);

CREATE TABLE HORARIO
(	
	HORA_ID_HORARIO					INT 			NOT NULL 	AUTO INCREMENT,
	HORA_DT_REGISTRO				DATETIME		NOT NULL,
	HORA_HR_SAIDA					TIME       		NOT NULL,
	LINH_ID_LINHA					INT 			NOT NULL,
	VEIC_ID_VEICULO					INT 			NOT NULL,
	PRIMARY KEY(HORA_ID_HORARIO),
	FOREIGN KEY(LINH_ID_LINHA) 	 REFERENCES LINHA(LINH_ID_LINHA),
	FOREIGN KEY(VEIC_ID_VEICULO) REFERENCES VEICULO(VEIC_ID_VEICULO)
);

CREATE TABLE TERMINAL_HORARIO
(
	TEHO_DT_REGISTRO 				DATETIME 		NOT NULL,
	TEHO_HR_SAIDA					TIME 			NOT NULL,
	TERM_ID_TERMINAL				INT 			NOT NULL,
	HORA_ID_HORARIO					INT 			NOT NULL,
	PRIMARY KEY(TERM_ID_TERMINAL, HORA_ID_HORARIO)				
);

CREATE TABLE HORARIO_FERIADO
(	
	FERI_ID_FERIADO					INT 			NOT NULL,
	HORA_ID_HORARIO					INT             NOT NULL,
	PRIMARY KEY(FERI_ID_FERIADO,HORA_ID_HORARIO)
);

CREATE TABLE HORARIO_DIAS
(	
	DIAS_ID_DIAS_SEMANA				INT 			NOT NULL,
	HORA_ID_HORARIO					INT 			NOT NULL,
	PRIMARY KEY(DIAS_ID_DIAS_SEMANA, HORA_ID_HORARIO)
);














