DROP DATABASE IF EXISTS MRVBIB;
-- DROP USER IF EXISTS 'coletor'@'localhost';

CREATE DATABASE MRVBIB;
CREATE USER 'coletor'@'localhost' IDENTIFIED BY 'ifes2017';
GRANT INSERT, SELECT ON MRVBIB.* TO 'coletor'@'localhost'; 

USE MRVBIB;

CREATE TABLE DADO_GPS
(
	DADO_ID_DADO_GPS		INT NOT NULL AUTO_INCREMENT,
	DADO_CD_VEICULO			CHAR(4) NOT NULL,
	DADO_VL_LATITUDE 		DECIMAL(10, 6) NOT NULL,
	DADO_SG_ORIENTACAO_LATITUDE	CHAR(1) NOT NULL,
	DADO_VL_LONGITUDE 		DECIMAL(10,6) NOT NULL,
	DADO_SG_ORIENTACAO_LONGITUDE	CHAR(1) NOT NULL,
	DADO_VL_VELOCIDADE 		DECIMAL(10, 6) NOT NULL, 
	DADO_DT_CAPTURA			DATETIME NOT NULL,
	DADO_DT_REGISTRO		DATETIME NOT NULL,

	PRIMARY KEY(DADO_ID_DADO_GPS)
);

DELIMITER @@
DROP TRIGGER IF EXISTS TRG_DADO_GPS_INS @@
CREATE TRIGGER TRG_DADO_GPS_INS
BEFORE INSERT ON DADO_GPS
FOR EACH ROW
BEGIN
	DECLARE MENSAGEM_ERRO VARCHAR(128);
	DECLARE DADO_GPS_ENCONTRADO INT;
	SELECT COUNT(1) INTO DADO_GPS_ENCONTRADO FROM DADO_GPS WHERE NEW.DADO_CD_VEICULO = DADO_CD_VEICULO AND NEW.DADO_DT_CAPTURA = DADO_DT_CAPTURA;
	IF DADO_GPS_ENCONTRADO > 0 THEN
		SET MENSAGEM_ERRO = CONCAT('TRG_DADO_GPS_INS - [DADO_CD_VEICULO] E [DADO_DT_CAPTURA] JÁ EXISTEM PARA: ', NEW.DADO_CD_VEICULO, ' E ', CAST(NEW.DADO_DT_CAPTURA AS CHAR), '.');
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MENSAGEM_ERRO;
	END IF;
END @@
DELIMITER ;